# Generated by Django 3.0.8 on 2020-12-01 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ahemdabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bengaluru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('topic', models.CharField(max_length=1000)),
                ('desc', models.CharField(default='description', max_length=500)),
                ('content', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 12, 1, 22, 30, 5, 271358))),
            ],
        ),
        migrations.CreateModel(
            name='chennai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='diseaseApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=3000)),
                ('type_disease', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='diseaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='diseaseImage/image')),
                ('causes_symptoms', models.CharField(default='', max_length=5000)),
                ('prevention', models.CharField(default='', max_length=5000)),
                ('description', models.CharField(default='', max_length=3000)),
                ('treatment', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='hyderabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='labBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('pcontact', models.IntegerField()),
                ('pemail', models.CharField(max_length=30)),
                ('page', models.IntegerField()),
                ('pgender', models.CharField(max_length=5)),
                ('lab_id', models.IntegerField()),
                ('lab_city', models.CharField(max_length=30)),
                ('lab_suburb', models.CharField(max_length=30)),
                ('lab_name', models.CharField(max_length=30)),
                ('test_name', models.CharField(max_length=30)),
                ('test_date', models.DateField()),
                ('test_time', models.CharField(max_length=30)),
                ('bookingStatus', models.CharField(default='No', max_length=5)),
                ('testStatus', models.CharField(default='No', max_length=15)),
                ('fasting', models.CharField(default='no', max_length=15)),
                ('postprandal', models.CharField(default='no', max_length=15)),
                ('report', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='mumbai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=50)),
                ('lab_address', models.CharField(default='', max_length=500)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_image', models.ImageField(default='', upload_to='patient/image')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.CharField(max_length=50)),
                ('patient_phone', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=6)),
                ('patient_age', models.IntegerField()),
                ('patient_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=50)),
                ('lab_address', models.CharField(default='', max_length=500)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
