# Generated by Django 3.0.8 on 2020-12-06 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20201201_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 11, 57, 51, 329256)),
        ),
        migrations.AlterField(
            model_name='labbook',
            name='report',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='patientmessage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 11, 57, 51, 330254)),
        ),
    ]
