# Generated by Django 3.0.8 on 2020-12-07 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20201207_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 19, 9, 309776)),
        ),
        migrations.AlterField(
            model_name='patientmessage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 19, 9, 310773)),
        ),
    ]
