# Generated by Django 3.0.8 on 2021-01-08 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20201214_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 16, 11, 47, 216835)),
        ),
        migrations.AlterField(
            model_name='patientmessage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 16, 11, 47, 217832)),
        ),
    ]
