# Generated by Django 3.0.8 on 2020-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_age', models.SmallIntegerField()),
                ('doc_gender', models.CharField(max_length=10)),
                ('doc_email', models.CharField(max_length=100)),
                ('doc_contact', models.IntegerField()),
                ('doc_speciality', models.CharField(max_length=50)),
                ('doc_experience', models.IntegerField()),
                ('doc_testimonials', models.TextField(max_length=5000)),
                ('doc_achievements', models.TextField(max_length=10000, null=True)),
                ('doc_password', models.CharField(default=' ', max_length=100)),
            ],
        ),
    ]
