# Generated by Django 3.0.8 on 2020-12-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20201201_2234'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='unsent', max_length=30)),
                ('from_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patient.patient')),
                ('to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doctor.DoctorProfile')),
            ],
        ),
    ]
