# Generated by Django 3.0.8 on 2020-12-07 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20201206_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 15, 27, 922970)),
        ),
    ]
