# Generated by Django 3.0.8 on 2020-12-07 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20201207_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 19, 9, 451752)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='report',
            field=models.FileField(null=True, upload_to='prescriptions'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 19, 9, 452753)),
        ),
    ]
