# Generated by Django 3.0.8 on 2020-12-14 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20201207_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 11, 32, 5, 794460)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 11, 32, 5, 795491)),
        ),
    ]
