# Generated by Django 3.0.8 on 2021-01-08 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20201214_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 16, 11, 47, 299747)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 16, 11, 47, 299747)),
        ),
    ]
