# Generated by Django 3.0.8 on 2021-01-08 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20210108_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 21, 8, 3, 893436)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 21, 8, 3, 893436)),
        ),
    ]
